#!/bin/bash
# =============================================================================
# Dynamic Labyrinth - Nginx Entrypoint
# =============================================================================
# Ensures the nginx map file exists before starting nginx.
# The map file is in a shared volume and may not exist on first boot.
# =============================================================================

set -e

MAP_FILE="/etc/nginx/maps/honeytrap_upstream.map"
MAP_DIR="/etc/nginx/maps"

# Ensure maps directory exists and is writable
mkdir -p "$MAP_DIR"

# Create default map file if it doesn't exist
if [ ! -f "$MAP_FILE" ]; then
    echo "Creating default nginx map file at $MAP_FILE"
    cat > "$MAP_FILE" << 'EOF'
# =============================================================================
# Dynamic Labyrinth - Honeytrap Upstream Map
# =============================================================================
# Generated by entrypoint - will be updated by Orchestrator
# =============================================================================

map $cookie_dlsess $honeytrap_upstream {
    default "level1_pool";
}
EOF
    echo "Default map file created"
else
    echo "Nginx map file already exists at $MAP_FILE"
fi

# Validate nginx configuration
echo "Validating nginx configuration..."
nginx -t

# Execute the original command (nginx)
echo "Starting nginx..."
exec "$@"
