# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/base.json
# golangci-lint v1.x configuration for honeytrap (legacy codebase)
# Note: Using base.json schema to avoid v2 schema validation errors
# This config is compatible with golangci-lint v1.64.x

run:
  timeout: 5m
  modules-download-mode: readonly
  issues-exit-code: 0
  skip-dirs:
    - vendor
    - pb

output:
  format: colored-line-number

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 0
  misspell:
    locale: US
  dupl:
    threshold: 600
  goconst:
    min-occurrences: 5
  gocyclo:
    min-complexity: 180
  lll:
    line-length: 750

linters:
  disable-all: true
  enable:
    - gofmt
    - ineffassign
    - staticcheck
    - unused
    - unparam
    - gosimple
    - dupl
    - gocyclo
    - nakedret
    - lll

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
    - linters:
        - gocyclo
      source: "func "
